branch #105 ;_;
musabd96/Schoolsync pull request #150
Opened 2024-01-22 19:42 UTC by Pepparmint

2024-01-22 19:46 UTC, Pepparmint commented
DateTime DateOfBirth förstår jag inte, den vill inte funka så kommentera bort den

2024-01-22 20:08 UTC, musabd96 commented on Infrastructure/Repositories/Teachers/ITeacherRepository.cs
> +                              string LastName, //DateTime DateOfBirth,
Varför har du kommentar här? DateTime DateOfBirth Det kommer inte lägga till nya födelsedatum i Db annars.

2024-01-22 20:10 UTC, musabd96 commented on Infrastructure/Repositories/Teachers/TeacherRepository.cs
> +        public Task<Teacher> UpdateTeacher(Guid id, string FirstName, string LastName, string Address, string PhoneNumber, string Email, CancellationToken cancellationToken)
Du kan lägga till här DateTime DateOfBirth. Du kommer inte få nån error

2024-01-22 20:21 UTC, musabd96 commented on ReactApp/ReactApp.Server/Controllers/TeacherController/TeacherController.cs
> +        public async Task<IActionResult> UpdateTeacher(Guid teacherId, [FromBody] UpdateTeacherCommand updateTeacherCommand)
updateTeacherCommand kommer inte Updatera. Du behöver här TeacherDto. Och flytta Guid erfter TeacherDto.

2024-01-22 20:22 UTC, musabd96 requested changes
Ändra Teachercontroller som har kommetar.

Du behöver inte kommetar i IteacherRepo DateTime Birdth annars kommer inte lägga till Db nya födelsdatum.

2024-01-23 17:53 UTC, musabd96 approved these changes

2024-01-23 17:54 UTC, merged